server:
  port: 8182

spring:
  datasource:
    password: w0519
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.71:3306/petsAdoption_pets?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true

  application:
    name: pets

  cloud:
    nacos:
      server-addr: 192.168.124.71:8848
      username: nacos
      password: nacos
    alibaba:
      seata:
        tx-service-group: default_tx_group

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 2MB


seata:
  # seata注册中心
  registry:
    type: nacos
    # 所在地址
    nacos:
      server-addr: 192.168.124.71:8848
      username: nacos
      password: nacos
      application: seata-server  # 应用名称
      group: SEATA_GROUP   # 应用组名
  # seata配置中心
  config:
    type: nacos
    nacos:
      server-addr: 192.168.124.71:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP


dubbo:
  protocol:    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1  #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
  registry:
    #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    address: spring-cloud://192.168.124.71:8848
  #  cloud:
#    subscribed-services: user  # 订阅的提供者名称
  scan:
    base-packages: com.petsAdoption.pets.service.impl
  cloud:
    subscribed-services: