spring:
  application:
    name: wish-list

  datasource:
    username: root
    password: w0519
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.71:3306/petsAdoption_wishList?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

  cloud:
    nacos:
      server-addr: 192.168.124.71:8848
      username: nacos
      password: nacos
  main:
    allow-bean-definition-overriding:
      true

mybatis-plus:
  configuration:
    # 关闭自动驼峰转换
    #    map-underscore-to-camel-case: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

server:
  port: 8083

dubbo:
  scan:
    base-packages: com.petsAdoption.wishList.service.impl
  protocol:    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1  #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
  registry:
    #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    address: spring-cloud://192.168.124.71:8848
  cloud:
    subscribed-services: user,pets  # 订阅的提供者名称
  consumer:
    check: false  #关闭订阅服务是否启动的检查【检查时，没有服务提供者会报错】
