server:
  port: 8089

spring:
  cloud:
    nacos:
      password: naocs
      username: nacos
      server-addr: 192.168.124.71:8848
  application:
    name: business

  datasource:
    password: w0519
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.124.71:3306/petsAdoption_business?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true

