server:
  port: 8086

spring:
  application:
    name: order

  resources:
    static-locations: classpath:/static

  datasource:
    username: root
    password: 20010519Smxy
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.28.107:3306/petsAdoption_order?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true

  cloud:
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
#      事物分组
    alibaba:
      seata:
        tx-service-group: default_tx_group

seata:
  data-source-proxy-mode:
  # seata注册中心
  registry:
    type: nacos
    # 所在地址
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
      application: seata-server  # 应用名称
      group: SEATA_GROUP   # 应用组名
  # seata配置中心
  config:
    type: nacos
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP

mybatis-plus:
  configuration:
    # 关闭自动驼峰转换
    #    map-underscore-to-camel-case: false
    # 打印sql
    call-setters-on-nulls: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000