spring:
  servlet:
    multipart:
      # 最大上传文件大小
      max-file-size: 10MB
      # 最大请求文件大小
      max-request-size: 10MB
  cloud:
    nacos:
      password: naocs
      username: nacos
      server-addr: 43.142.28.107:8848
  application:
    name: file

server:
  port: 9008

feign:
  hystrix:
    enabled: true