server:
  port: 8082

spring:
  datasource:
    password: 20010519Smxy
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.142.28.107:3306/petsAdoption_pets?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true

  application:
    name: pets

  cloud:
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
    alibaba:
      seata:
        tx-service-group: default_tx_group

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 2MB

mybatis-plus:
  configuration:
    # 关闭自动驼峰转换
#    map-underscore-to-camel-case: false
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


seata:
  # seata注册中心
  registry:
    type: nacos
    # 所在地址
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
      application: seata-server  # 应用名称
      group: SEATA_GROUP   # 应用组名
  # seata配置中心
  config:
    type: nacos
    nacos:
      server-addr: 43.142.28.107:8848
      username: nacos
      password: nacos
      group: SEATA_GROUP